baseurl = "https://joeys-rchs.pages.dev/"
title = "St. Joseph’s RC High School"
languageCode = "en"
DefaultContentLanguage = "en"
paginate = "10" # Number of posts per page
theme = "hugo-dpsg"

[Params]
  description = "Welcome to St. Joseph&#8217;s Roman Catholic High School Whether you are looking for information about our school or arrived here by chance, you are very welcome. We hope that you can sense the warm family values of our school." # Site description. Used in meta description

  copyright = "" 

  opengraph = true # Enable OpenGraph if true

  schema = true # Enable Schema

  twitter_cards = true # Enable Twitter Cards if true
  
  readmore = true # Show "Read more" button in list if true

  authorbox = true # Show authorbox at bottom of pages if true

  toc = true # Enable Table of Contents

  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true

  indexPager = true # Show pager navigation on index page

  post_meta = ["author", "date", "categories"] # Order of post meta information

  mainSections = ["posts", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget

  dateformat = "02.01.2006" # Change the format of dates

  [Author] # Used in authorbox
  name = "Mansoor Barri"
  bio = "11 Vincent"
  avatar = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.onlinewebfonts.com%2Fsvg%2Fimg_87237.png&f=1&nofb=1&ipt=fea539d42efef230dc394aa8d5e4e2598ca8528849f8f76056bbaea0e56b2987&ipo=images"

[Params.style.vars]
  highlightColor = "#003056" # Override main theme color

[Params.logo]
  image = "https://joeys-rchs.pages.dev/assets/logo.png" 
  header = "https://joeys-rchs.pages.dev/assets/banner.png"
  title = "St. Joseph’s RC High School" 
  # subtitle = "St. Joseph's RC High School prioritizes the safety and well-being of children and young people, and requires all staff and volunteers to share this commitment."

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "categories", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  facebook = "StJosephsRCHS"
  twitter = "Joeys_rchs"
  instagram = "joeys_rchs"
  linkedin = "company/st-joseph-s-rc-high-school-horwich"
  email = "office@st-josephs.bolton.sch.uk"


[Params.footer]
  right = '''
  [Contact Us](/contact-us) ‎‎
  [Privacy Policy](/privacy) ‎‎
  [Sitemap](/sitemap.xml)
  '''
# Custom menu items, normally controlled via front matter in /content files
[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "Info"
    name = "Information"
    url = "/information/"
    weight = 3

  [[menu.main]]
    identifier = "Curriculum"
    name = "Curriculum"
    url = "/Curriculum/"
    weight = 4

  [[menu.main]]
    identifier = "Our Community"
    name = "Our Community"
    url = "/our-community/"
    weight = 5

  [[menu.main]]
    identifier = "Student Blog"
    name = "Student Blog"
    url = "/blog/"
    weight = 6

  [[menu.main]]
    identifier = "Contact"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 7